remove revision. is not necessary (#147)

diff --git a/integration-tests/tasks/rhtap-e2e.yaml b/integration-tests/tasks/rhtap-e2e.yaml
--- a/integration-tests/tasks/rhtap-e2e.yaml
+++ b/integration-tests/tasks/rhtap-e2e.yaml
@@ -28,6 +28,7 @@ spec:
   steps:
     - name: e2e-test
       image: $(params.rhtap-e2e-container)
+      workingDir: /workspace
       volumeMounts:
         - name: rhtap-cli-volume
           mountPath: /usr/local/rhtap-cli-install
@@ -39,24 +40,38 @@ spec:
         - name: JOB_SPEC
           value: $(params.job-spec)
       script: |
-        #!/bin/sh
-
-        set -o errexit
-        set -o nounset
-        set -o pipefail
-
         # Log into OpenShift
         $(params.ocp-login-command)
 
+        echo "[DEBUG] JOB_SPEC: $JOB_SPEC"
+
         export GIT_REPO="$(echo "$JOB_SPEC" | jq -r '.git.git_repo')"
+        echo "[INFO] GIT_REPO is set to $GIT_REPO"
+
+        if [ -z "$GIT_REPO" ]; then
+          echo "[ERROR] GIT_REPO is not set in JOB_SPEC"
+          exit 1
+        fi
 
         if [ "$GIT_REPO" = "rhtap-e2e" ]; then
-          export SOURCE_REPO_URL="$(echo "$JOB_SPEC" | jq -r '.git.source_repo_url' | sed 's#https://github.com/##')"
+          export SOURCE_REPO_URL="$(echo "$JOB_SPEC" | jq -r '.git.source_repo_url')"
           export SOURCE_REPO_BRANCH="$(echo "$JOB_SPEC" | jq -r '.git.source_repo_branch')"
 
+          echo "[INFO] SOURCE_REPO_URL is set to $SOURCE_REPO_URL"
+          echo "[INFO] SOURCE_REPO_BRANCH is set to $SOURCE_REPO_BRANCH"
+
+          if [ -z "$SOURCE_REPO_URL" ] || [ -z "$SOURCE_REPO_BRANCH" ]; then
+            echo "[ERROR] SOURCE_REPO_URL or SOURCE_REPO_BRANCH is not set"
+            exit 1
+          fi
+
           echo -e "[INFO] Running e2e tests from source: $SOURCE_REPO_URL and branch $SOURCE_REPO_BRANCH"
-          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/$SOURCE_REPO_URL/$SOURCE_REPO_BRANCH/integration-tests/scripts/rhtap-e2e-runner.sh)"
+          curl -fsSL https://raw.githubusercontent.com/$SOURCE_REPO_URL/$SOURCE_REPO_BRANCH/integration-tests/scripts/rhtap-e2e-runner.sh -o rhtap-e2e-runner.sh
+          chmod +x rhtap-e2e-runner.sh 
+          ./rhtap-e2e-runner.sh
         else
-          echo -e "[INFO] Running e2e tests from source: redhat-appstudio/rhtap-e2e and branch main"
-          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/redhat-appstudio/rhtap-e2e/main/integration-tests/scripts/rhtap-e2e-runner.sh)"
+          echo -e "[INFO] Running e2e tests from: redhat-appstudio/rhtap-e2e and branch main"
+          curl -fsSL https://raw.githubusercontent.com/redhat-appstudio/rhtap-e2e/main/integration-tests/scripts/rhtap-e2e-runner.sh -o rhtap-e2e-runner.sh
+          chmod +x rhtap-e2e-runner.sh
+          ./rhtap-e2e-runner.sh
         fi
